[package]
name = "backend"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jaakko.hannikainen@solita.fi>"]
edition = "2018"

[dependencies]
gotham = "0.4.0"
gotham_derive = "0.4.0"
postgres = "0.15.2"
hyper = "0.12.35"
serde = "1.0.60"
serde_json = "1.0.40"
lazy_static = "1.4.0"
