[package]
name = "frontend"
version = "0.1.0"
authors = ["Jaakko Hannikainen <jaakko.hannikainen@solita.fi>"]
edition = "2018"

[dependencies]
failure = "0.1"
log = "0.4"
stdweb = "0.4"
types = { path = "../types" }
web_logger = "0.1"
yew = "0.8.0"
